# Generated by Django 5.0.4 on 2024-12-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, null=True, verbose_name='Blog Title')),
                ('subtitle', models.CharField(max_length=121, null=True, verbose_name='Blog Sub-Title')),
                ('bg_image', models.ImageField(null=True, upload_to='images/blog/', verbose_name="Title's Background Picture")),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('intro', models.TextField(blank=True, null=True, verbose_name='Introductory Text')),
                ('header_1', models.CharField(blank=True, max_length=70, null=True, verbose_name='Content Header 1')),
                ('content_1', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('header_2', models.CharField(blank=True, max_length=70, null=True, verbose_name='Content Header 2')),
                ('content_2', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
