# Generated by Django 5.0.4 on 2024-12-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/blog/blog-image'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/blog/blog-image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='bg_image',
            field=models.ImageField(null=True, upload_to='images/blog/blog-images', verbose_name="Title's Background Picture"),
        ),
    ]
