# Generated by Django 5.1.3 on 2024-11-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_brochure_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='files/brochures', verbose_name='Brochure PDF'),
        ),
    ]
